# Generated by Django 6.0.6 on 2026-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='role',
            field=models.CharField(choices=[('MAIN_ADMIN', 'Админ'), ('MEDIA', 'СМИ'), ('ORGANIZER', 'Орг')], default='MEDIA', max_length=20),
        ),
    ]
