# Generated by Django 6.0.6 on 2026-06-09 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_invitecode_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('CAMERA', 'Камера'), ('LENS', 'Объектив'), ('LIGHT', 'Свет'), ('AUDIO', 'Звук'), ('OTHER', 'Другое')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Доступно'), ('MAINTENANCE', 'Ремонт'), ('RETIRED', 'Списано')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('ISSUED', 'Выдано'), ('RETURN_REQUESTED', 'Запрос на возврат'), ('RETURNED', 'Возвращено'), ('REJECTED', 'Отклонено')], default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='events.equipment')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_loans', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
