# Generated by Django 5.0 on 2026-08-10 18:30

from django.db import migrations, models

def create_default_skills(apps, schema_editor):
    Skill = apps.get_model('events', 'Skill')
    # Default skills based on the old SKILL_CHOICES
    Skill.objects.get_or_create(code='ANY', defaults={'name': 'Любой', 'is_default': True})
    Skill.objects.get_or_create(code='PRO', defaults={'name': 'Профи', 'is_pro': True})
    Skill.objects.get_or_create(code='VIDEO', defaults={'name': 'Видео'})

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_equipmentloan_loan_end_equipmentloan_loan_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_pro', models.BooleanField(default=False, help_text='Может брать любые задачи')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео'), ('ALL', 'Всё вместе')], default='PHOTO', max_length=10)),
                ('required_skill', models.CharField(default='ANY', max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=1)),
                ('equipment', models.ManyToManyField(blank=True, to='events.equipment')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='required_skill',
            field=models.CharField(default='ANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_level',
            field=models.CharField(default='ANY', max_length=20, verbose_name='Уровень'),
        ),
        migrations.RunPython(create_default_skills, reverse_code=migrations.RunPython.noop),
    ]
