# Generated by Django 5.2.17 on 2026-08-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_skill_eventtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),

        migrations.AddField(
            model_name='event',
            name='short_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий комментарий'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_events',
            field=models.BooleanField(default=False, verbose_name='Может одобрять мероприятия'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_warehouse',
            field=models.BooleanField(default=False, verbose_name='Может управлять складом'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_all_events',
            field=models.BooleanField(default=False, verbose_name='Может просматривать все мероприятия'),
        ),

        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.location'),
        ),
    ]
