# Generated by Django 5.2.17 on 2026-09-08 09:23

import events.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_comment_id_alter_equipment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', events.models.UserManager()),
            ],
        ),
    ]
