# Generated by Django 6.0.6 on 2026-06-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_updatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='role',
            field=models.CharField(choices=[('MAIN_ADMIN', 'Админ'), ('MEDIA', 'СМИ'), ('ORGANIZER', 'Орг')], default='ORGANIZER', max_length=20),
        ),
    ]
